[book]
authors = ["شركة Ankitects المملوكة المحدودة ومتطوعون"]
language = "ar"
src = "src"
title = "دليل استخدام أنكي"

[build]
create-missing = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/abdnh/anki-manual"
additional-css = ["css/kbd.css", "css/rtl.css"]

[output.linkcheck]
optional = true
warning-policy = "warn"
follow-web-links = true
exclude = [
  'microsoft.com',
  'twitter.com',
  'stackexchange.com',
  'stackoverflow.com',
  'https://github.com/open-spaced-repetition/fsrs4anki#add-on-compatibility',
  'support.google.com',
  'wikiwiki.jp',
  'web.archive.org',
]

[output.html.fold]
enable = true
level = 0
